// Sample exported MultiLineChartWidget - Auto-generated by Dashboard Builder
import React from "react";
import {
  ResponsiveContainer,
  CartesianGrid,
  XAxis,
  YAxis,
  Tooltip,
  Legend,
  LineChart, Line,
  BarChart, Bar, Cell,
  AreaChart, Area,
  PieChart, Pie,
  FunnelChart, Funnel, LabelList
} from "recharts";

export default function TestMultiLineDashboard() {
  const styles = {
    "page": {
      "fontFamily": "ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial",
      "background": "#f5f5f5",
      "color": "#525252",
      "padding": 16
    },
    "container": {
      "width": "100%",
      "margin": "0"
    },
    "row": {
      "display": "flex",
      "alignItems": "stretch",
      "gap": 8,
      "margin": "24px 0px"
    },
    "card": {
      "background": "#ffffff",
      "border": "1px solid rgba(0,0,0,0.08)",
      "borderRadius": 12,
      "padding": 16,
      "height": "100%",
      "boxShadow": "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)",
      "fontFamily": "'Figtree', sans-serif"
    },
    "title": {
      "fontSize": 14,
      "fontWeight": 600,
      "marginBottom": 16,
      "color": "#1f2937",
      "fontFamily": "'Figtree', sans-serif",
      "paddingBottom": 8,
      "borderBottom": "1px solid #f3f4f6"
    }
  };

  // ----- inline data -----
  const data_test_multi_line_1 = [
    { name: "Jan", value: 40, value2: 32, value3: 28 },
    { name: "Feb", value: 32, value2: 28, value3: 35 },
    { name: "Mar", value: 50, value2: 45, value3: 38 },
    { name: "Apr", value: 45, value2: 38, value3: 42 },
    { name: "May", value: 62, value2: 55, value3: 48 },
    { name: "Jun", value: 55, value2: 48, value3: 52 }
  ];

  // ----- row count variables -----
  const rowCount_row_1 = 1;

  return (
    <div style={styles.page}>
      <div style={styles.container}>
        <div key="row-1" style={styles.row}>
          <div key="test-multi-line-1" style={{...styles.card, flexBasis: `calc((100% - ${Math.min(4, rowCount_row_1) - 1}*8px) / ${Math.min(4, rowCount_row_1)})`}}>
            {/* Widget Title */}
            <div style={styles.title}>
              Test Multi-Line Chart
            </div>
            
            {/* Chart Container */}
            <div style={{ width: "100%", height: 300 }}>
              <ResponsiveContainer>
                <LineChart 
                  data={data_test_multi_line_1}
                  margin={{ top: 10, right: 10, left: 0, bottom: 5 }}
                >
                  {/* Grid */}
                  <CartesianGrid 
                    strokeDasharray="3 3"
                    stroke="#e5e7eb"
                    horizontal={true}
                    vertical={false}
                  />
                  
                  {/* X Axis */}
                  <XAxis 
                    dataKey="name"
                    tick={{
                      fontSize: 12,
                      fill: "#6b7280",
                      fontFamily: "'Figtree', sans-serif"
                    }}
                    axisLine={{ stroke: "#e5e7eb" }}
                    tickLine={false}
                    padding={{ left: 10, right: 10 }}
                  />
                  
                  {/* Y Axis */}
                  <YAxis 
                    tick={{
                      fontSize: 12,
                      fill: "#6b7280",
                      fontFamily: "'Figtree', sans-serif"
                    }}
                    axisLine={false}
                    tickLine={false}
                    width={30}
                  />
                  
                  {/* Tooltip */}
                  <Tooltip 
                    contentStyle={{
                      backgroundColor: "#ffffff",
                      border: "1px solid #e5e7eb",
                      borderRadius: 6,
                      boxShadow: "0 2px 5px rgba(0,0,0,0.1)",
                      color: "#1f2937",
                      fontFamily: "'Figtree', sans-serif"
                    }}
                    cursor={{
                      stroke: "#9ca3af",
                      strokeWidth: 1,
                      strokeDasharray: "3 3"
                    }}
                    formatter={(value, name) => [value?.toLocaleString?.() ?? value, name]}
                  />
                  
                  {/* Legend */}
                  <Legend 
                    wrapperStyle={{ 
                      paddingTop: 10,
                      fontFamily: "'Figtree', sans-serif",
                      fontSize: 12
                    }} 
                    iconType="circle" 
                  />
                  
                  {/* Primary Line (Series 1) */}
                  <Line 
                    name="Revenue"
                    type="monotone"
                    dataKey="value"
                    stroke="#27D0FC"
                    strokeWidth={3}
                    dot={{
                      fill: "#27D0FC",
                      strokeWidth: 2,
                      r: 4
                    }}
                    activeDot={{
                      r: 6,
                      stroke: "#27D0FC",
                      strokeWidth: 2,
                      fill: "white"
                    }}
                    animationDuration={1500}
                  />
                  
                  {/* Secondary Line (Series 2) */}
                  <Line 
                    name="Expenses"
                    type="monotone"
                    dataKey="value2"
                    stroke="#10B981"
                    strokeWidth={2.5}
                    dot={{
                      fill: "#10B981",
                      strokeWidth: 2,
                      r: 3
                    }}
                    activeDot={{
                      r: 5,
                      stroke: "#10B981",
                      strokeWidth: 2,
                      fill: "white"
                    }}
                    animationDuration={1700}
                  />
                  
                  {/* Tertiary Line (Series 3) */}
                  <Line 
                    name="Profit"
                    type="monotone"
                    dataKey="value3"
                    stroke="#F59E0B"
                    strokeWidth={2.5}
                    dot={{
                      fill: "#F59E0B",
                      strokeWidth: 2,
                      r: 3
                    }}
                    activeDot={{
                      r: 5,
                      stroke: "#F59E0B",
                      strokeWidth: 2,
                      fill: "white"
                    }}
                    animationDuration={1900}
                  />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
